### ISSUE TITLE
ValueError in tablesize_aggregated() and summary()

### ISSUE THREAD

**Issue by BelanaZ** [Stemanz/restring#2]
When using the functions tablesize_aggregated() and summary() in gears.py I get a ValueError in lines 477-478 and 417-418 because the argument "ascending" in the pandas function df.sort_values() expects type bool but receives type str:

```
477    df = pd.read_csv(StringIO(returnstring), index_col=0, sep="\t").sort_values\
478        (by="term", ascending="True")
```

**Comment by Stemanz** [comment]
Thanks for spotting this. I've fixed the code (there was another similar issue elsewhere), and re-checked the entire procedure with the sample input files in https://github.com/Stemanz/restring/tree/main/sample_tables, now it's OK again.
I'll be shortly updating the version number so that the fixed code can be installed via pip.

**Comment by BelanaZ** [comment]
Thank you for fixing this so quickly!
